name: store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  file_picker: ^8.0.3
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_image_compress: ^2.3.0
  flutter_localization: ^0.2.0
  flutter_masked_text2: ^0.9.1
  http: ^1.2.1
  intl: ^0.18.1
  provider: ^6.1.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
 
